# docker-compose.yml
# Définit les services, les réseaux et les volumes pour l'application Icare.

version: '3.8'

services:
  # Service Backend (Rust)
  icare-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: icare-backend
    ports:
      - "8000:8000"
    volumes:
      - ./src/core:/app/src
    environment:
      - ROCKET_ADDRESS=0.0.0.0
    restart: unless-stopped

  # Service Frontend (React + Nginx)
  icare-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: icare-frontend
    ports:
      - "3000:80" # Nginx écoute sur le port 80 dans le conteneur
    depends_on:
      - icare-backend
    restart: unless-stopped

  # Time-series Database
  timescale:
    image: timescale/timescaledb-ha:pg15-latest
    container_name: icarus-timescale
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_DB=icarus_metrics
    volumes:
      - timescale-data:/var/lib/postgresql/data
    networks:
      - icarus-net
    secrets:
      - db_password

networks:
  icarus-net:
    driver: bridge

volumes:
  timescale-data:

secrets:
  db_password:
    file: ./secrets/db_password.txt