version: '3.8'

services:
  # Backend Rust Service
  icare-core:
    build:
      context: .
      dockerfile: ./src/core/Dockerfile
    container_name: icare-core-api
    ports:
      - "8080:8080"
    volumes:
      - ./src/core:/usr/src/app/src/core
    environment:
      - RUST_LOG=info
    restart: unless-stopped

  # Frontend React Service
  icare-ui:
    build:
      context: .
      dockerfile: ./src/ui/Dockerfile
    container_name: icare-ui-web
    ports:
      - "3000:80"
    depends_on:
      - icare-core
    restart: unless-stopped

  # Time-series Database
  timescale:
    image: timescale/timescaledb-ha:pg15-latest
    container_name: icarus-timescale
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_DB=icarus_metrics
    volumes:
      - timescale-data:/var/lib/postgresql/data
    networks:
      - icarus-net
    secrets:
      - db_password

networks:
  icarus-net:
    driver: bridge

volumes:
  timescale-data:

secrets:
  db_password:
    file: ./secrets/db_password.txt